# A journey of 1,000 lines starts with a single char

debug: false

#this defines the max ship parameters
#A value of -1 indicates no limit
ship-size:
  max-ship-blocks:  500
  max-ship-x-width: 32
  max-ship-height:  16
  max-ship-z-width: 32

allowed-blocks:
  - "#ANVIL"
  - "#ALL_SIGNS"
  - "#BAMBOO_BLOCKS"
  - "#BANNERS"
  - "#BARS"
  - "#BEDS"
  - "#BUTTONS"
  - "#CANDLES"
  - "#CHAINS"
  - "#COPPER"
  - "#DOORS"
  - "#FENCES"
  - "#FENCE_GATES"
  - "#FLOWER_POTS"
  - "#LANTERNS"
  - "#LIGHTNING_RODS"
  - "#LOGS"
  - "#PLANKS"
  - "#WOODEN_STAIRS"
  - "#TERRACOTTA"
  - "#WOODEN_SHELVES"
  - "#WOODEN_SLABS"
  - "#WOODEN_TRAPDOORS"
  - "#WOOL"
  - "#WOOL_CARPETS"
  - BARRIER
  - RED_SANDSTONE_STAIRS
  - ARMOR_STAND
  - BARREL
  - BELL
  - BOOKSHELF
  - CAMPFIRE
  - CARTOGRAPHY_TABLE
  - CAULDRON
  - CHEST
  - CHISELED_BOOKSHELF
  - COMPOSTER
  - COPPER_CHEST
  - CRAFTER
  - CRAFTING_TABLE
  - CRAFTING_TABLE
  - CREEPER_HEAD
  - CREEPER_WALL_HEAD
  - DECORATED_POT
  - DISPENSER
  - DRAGON_HEAD
  - DRAGON_WALL_HEAD
  - DROPPER
  - EMERALD
  - ENCHANTING_TABLE
  - ENDER_CHEST
  - END_ROD
  - FLETCHING_TABLE
  - FURNACE
  - HAY_BLOCK
  - HOPPER
  - ITEM_FRAME
  - GLOW_ITEM_FRAME
  - JACK_O_LANTERN
  - JIGSAW
  - LADDER
  - LECTERN
  - LIGHT
  - LOOM
  - NOTE_BLOCK
  - OBSERVER
  - OBSIDIAN
  - OCHRE_FROGLIGHT
  - PAINTING
  - PEARLESCENT_FROGLIGHT
  - PIGLIN_HEAD
  - PIGLIN_WALL_HEAD
  - PLAYER_HEAD
  - PLAYER_WALL_HEAD
  - REDSTONE_BLOCK
  - REDSTONE_LAMP
  - REDSTONE_TORCH
  - REDSTONE_WALL_TORCH
  - RED_CONCRETE
  - SCAFFOLDING
  - SEA_LANTERN
  - SKELETON_SKULL
  - SKELETON_WALL_SKULL
  - SMITHING_TABLE
  - SMOKER
  - SOUL_CAMPFIRE
  - STONECUTTER
  - STRING
  - TORCH
  - TRAPPED_CHEST
  - TRIPWIRE
  - VERDANT_FROGLIGHT
  - WALL_TORCH
  - WATER_CAULDRON
  - WHITE_CONCRETE
  - WITHER_SKELETON_SKULL
  - WITHER_SKELETON_WALL_SKULL
  - ZOMBIE_HEAD
  - ZOMBIE_WALL_HEAD
  - BLACK_STAINED_GLASS_PANE
  - BLUE_STAINED_GLASS_PANE
  - BROWN_STAINED_GLASS_PANE
  - CYAN_STAINED_GLASS_PANE
  - GRAY_STAINED_GLASS_PANE
  - GREEN_STAINED_GLASS_PANE
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - LIME_STAINED_GLASS_PANE
  - MAGENTA_STAINED_GLASS_PANE
  - ORANGE_STAINED_GLASS_PANE
  - PINK_STAINED_GLASS_PANE
  - PURPLE_STAINED_GLASS_PANE
  - RED_STAINED_GLASS_PANE
  - WHITE_STAINED_GLASS_PANE
  - YELLOW_STAINED_GLASS_PANE
  - BLACK_STAINED_GLASS
  - BLUE_STAINED_GLASS
  - BROWN_STAINED_GLASS
  - CYAN_STAINED_GLASS
  - GRAY_STAINED_GLASS
  - GREEN_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS
  - LIME_STAINED_GLASS
  - MAGENTA_STAINED_GLASS
  - ORANGE_STAINED_GLASS
  - PINK_STAINED_GLASS
  - PURPLE_STAINED_GLASS
  - RED_STAINED_GLASS
  - WHITE_STAINED_GLASS
  - YELLOW_STAINED_GLASS
  - BLACK_CONCRETE
  - BLUE_CONCRETE
  - BROWN_CONCRETE
  - CYAN_CONCRETE
  - GRAY_CONCRETE
  - GREEN_CONCRETE
  - LIGHT_BLUE_CONCRETE
  - LIGHT_GRAY_CONCRETE
  - LIME_CONCRETE
  - MAGENTA_CONCRETE
  - ORANGE_CONCRETE
  - PINK_CONCRETE
  - PURPLE_CONCRETE
  - RED_CONCRETE
  - WHITE_CONCRETE
  - YELLOW_CONCRETE
  - POTTED_ACACIA_SAPLING
  - POTTED_ALLIUM
  - POTTED_AZALEA_BUSH
  - POTTED_AZURE_BLUET
  - POTTED_BAMBOO
  - POTTED_BIRCH_SAPLING
  - POTTED_BLUE_ORCHID
  - POTTED_BROWN_MUSHROOM
  - POTTED_CACTUS
  - POTTED_CHERRY_SAPLING
  - POTTED_CLOSED_EYEBLOSSOM
  - POTTED_CORNFLOWER
  - POTTED_CRIMSON_FUNGUS
  - POTTED_CRIMSON_ROOTS
  - POTTED_DANDELION
  - POTTED_DARK_OAK_SAPLING
  - POTTED_DEAD_BUSH
  - POTTED_FERN
  - POTTED_FLOWERING_AZALEA_BUSH
  - POTTED_GOLDEN_DANDELION  
  - POTTED_JUNGLE_SAPLING
  - POTTED_LILY_OF_THE_VALLEY
  - POTTED_MANGROVE_PROPAGULE
  - POTTED_OAK_SAPLING
  - POTTED_OPEN_EYEBLOSSOM
  - POTTED_ORANGE_TULIP
  - POTTED_OXEYE_DAISY
  - POTTED_PALE_OAK_SAPLING
  - POTTED_PINK_TULIP
  - POTTED_POPPY
  - POTTED_RED_MUSHROOM
  - POTTED_RED_TULIP
  - POTTED_SPRUCE_SAPLING
  - POTTED_TORCHFLOWER
  - POTTED_WARPED_FUNGUS
  - POTTED_WARPED_ROOTS
  - POTTED_WHITE_TULIP
  - POTTED_WITHER_ROSE
    
    
    
